services:
  # 1. PostgreSQ: для реляційних даних (користувачі, профілі, траєкторії)
  postgres:
    image: postgres:15-alpine
    container_name: alp_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: adaptive_learning_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adaptive_network

  # 2. Neo4j: для Графа знань (концепції, пререквізити)
  neo4j:
    image: neo4j:5.12
    container_name: alp_neo4j
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
    networks:
      - adaptive_network

  # 3. MongoDB: для логування подій та поведінкових патернів
  mongodb:
    image: mongo:7.0
    container_name: alp_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - adaptive_network

  # 4. Redis: для кешування, сесій та як брокер для Celery
  redis:
    image: redis:7-alpine
    container_name: alp_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - adaptive_network

  user_service:
    build:
      context: ./backend/services/user_service
    container_name: alp_user_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password123@postgres:5432/adaptive_learning_db
      - SECRET_KEY=my-super-secret-key-for-jwt
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - postgres
    networks:
      - adaptive_network

  knowledge_graph_service:
    build:
      context: ./backend/services/knowledge_graph_service
    container_name: alp_kg_service
    ports:
      - "8001:8000"
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
    depends_on:
      - neo4j
    networks:
      - adaptive_network

  learning_path_service:
    build:
      context: ./backend/services/learning_path_service
    container_name: alp_path_service
    ports:
      - "8002:8000"
    environment:
      - USER_SERVICE_URL=http://user_service:8000
      - KG_SERVICE_URL=http://knowledge_graph_service:8000
    depends_on:
      - postgres
      - neo4j
    networks:
      - adaptive_network

# Томи для збереження даних
volumes:
  postgres_data:
  neo4j_data:
  mongo_data:
  redis_data:

# Мережа для взаємодії контейнерів
networks:
  adaptive_network:
    driver: bridge
