name: adaptive_learning_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  envied: ^1.3.1
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  dio: ^5.9.0
  intl: ^0.20.2
  flutter_svg: ^2.2.2
  lottie: ^3.3.2
  equatable: ^2.0.7
  theme_tailor_annotation: ^3.1.1
  talker_flutter: ^5.0.2
  talker_dio_logger: ^5.0.2
  talker_bloc_logger: ^5.0.2
  talker_logger: ^5.0.2
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  envied_generator: ^1.3.1
  build_runner: ^2.10.1
  flutter_gen_runner: ^5.12.0
  theme_tailor: ^3.1.1

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - assets/icons/
  #   - assets/lottie/

flutter_gen_runner:
  integrations:
    flutter_svg: true
    lottie: true
