name: adaptive_learning_app
description: "Personalized mobile application for adaptive learning."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Core ---
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  dio: ^5.9.0
  intl: ^0.20.2
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  jwt_decoder: ^2.0.1
  youtube_player_flutter: ^9.1.3
  webview_flutter: ^4.13.0

  # --- Storage & Env ---
  envied: ^1.3.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

  # --- UI ---
  flutter_svg: ^2.2.2
  lottie: ^3.3.2
  theme_tailor_annotation: ^3.1.1

  # --- Debugging ---
  talker_flutter: ^5.0.2
  talker_dio_logger: ^5.0.2
  talker_bloc_logger: ^5.0.2
  talker_logger: ^5.0.2

  # --- Service abstractions ---
  i_app_services:
    path: ./app_services/i_app_services

  # --- Basic implementation of services ---
  app_services:
    path: app_services/base/app_services

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- Code Generation ---
  build_runner: ^2.10.1
  envied_generator: ^1.3.1
  flutter_gen_runner: ^5.12.0
  theme_tailor: ^3.1.1

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - assets/icons/
  #   - assets/lottie/

# --- Flutter Gen ---
flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

# --- L10n ---
flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-dir: lib/l10n/gen
